"""initial schema

Revision ID: ed1ac17aa3b9
Revises:
Create Date: 2026-08-11 16:12:26.444082
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ed1ac17aa3b9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_setting",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_setting")),
    )
    op.create_table(
        "audit_log_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("actor_name", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("target_label", sa.String(length=512), nullable=True),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log_entry")),
    )
    with op.batch_alter_table("audit_log_entry", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_entry_action"), ["action"], unique=False)
        batch_op.create_index(
            "ix_audit_log_entry_action_time", ["action", "occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_entry_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_entry_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_entry_target_type"), ["target_type"], unique=False
        )

    op.create_table(
        "cx_application",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cx_application")),
    )
    with op.batch_alter_table("cx_application", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cx_application_name"), ["name"], unique=False)

    op.create_table(
        "cx_connection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=False),
        sa.Column("iam_base_url", sa.String(length=512), nullable=False),
        sa.Column("tenant_name", sa.String(length=256), nullable=False),
        sa.Column("api_base_url", sa.String(length=512), nullable=False),
        sa.Column("api_base_url_overridden", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("api_key_fingerprint", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cx_connection")),
    )
    op.create_table(
        "cx_group",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=True),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cx_group")),
    )
    with op.batch_alter_table("cx_group", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cx_group_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_cx_group_parent_id"), ["parent_id"], unique=False)

    op.create_table(
        "cx_project",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("repo_url", sa.String(length=1024), nullable=True),
        sa.Column("repo_id", sa.String(length=64), nullable=True),
        sa.Column("auto_triage_enabled", sa.Boolean(), nullable=True),
        sa.Column("auto_triage_config", sa.JSON(), nullable=True),
        sa.Column("pr_remediation_severities", sa.JSON(), nullable=True),
        sa.Column("ai_state_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cx_project")),
    )
    with op.batch_alter_table("cx_project", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cx_project_name"), ["name"], unique=False)

    op.create_table(
        "cx_user",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("auth_provider", sa.String(length=32), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("role_names", sa.JSON(), nullable=True),
        sa.Column("group_names", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cx_user")),
    )
    with op.batch_alter_table("cx_user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cx_user_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_cx_user_username"), ["username"], unique=False)

    op.create_table(
        "dimension_state",
        sa.Column("view_by", sa.String(length=16), nullable=False),
        sa.Column("supported", sa.Boolean(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("view_by", name=op.f("pk_dimension_state")),
    )
    op.create_table(
        "login_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(length=128), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempt")),
        sa.UniqueConstraint("identifier", "ip_address", name="identifier_ip"),
    )
    op.create_table(
        "scheduler_lock",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("holder", sa.String(length=128), nullable=True),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_scheduler_lock")),
    )
    op.create_table(
        "scheduler_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduler_run")),
    )
    with op.batch_alter_table("scheduler_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scheduler_run_started_at"), ["started_at"], unique=False
        )

    op.create_table(
        "unresolved_subject",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_key", sa.String(length=320), nullable=False),
        sa.Column("subject_name", sa.String(length=320), nullable=True),
        sa.Column("subject_email", sa.String(length=320), nullable=True),
        sa.Column("view_by", sa.String(length=16), nullable=False),
        sa.Column("credits_used", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("times_seen", sa.Integer(), nullable=False),
        sa.Column("mapped_user_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unresolved_subject")),
        sa.UniqueConstraint("subject_key", name=op.f("uq_unresolved_subject_subject_key")),
    )
    op.create_table(
        "usage_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("view_by", sa.String(length=16), nullable=False),
        sa.Column("period_param", sa.String(length=32), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=True),
        sa.Column("total_credits", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("pages_fetched", sa.Integer(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_snapshot")),
    )
    with op.batch_alter_table("usage_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usage_snapshot_collected_at"), ["collected_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_usage_snapshot_view_by"), ["view_by"], unique=False)
        batch_op.create_index(
            "ix_usage_snapshot_view_time", ["view_by", "collected_at"], unique=False
        )

    op.create_table(
        "utility_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("totp_secret_encrypted", sa.String(length=512), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_utility_user")),
    )
    with op.batch_alter_table("utility_user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_utility_user_username"), ["username"], unique=True)

    op.create_table(
        "credit_limit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("entity_label", sa.String(length=512), nullable=True),
        sa.Column("credit_limit", sa.Integer(), nullable=False),
        sa.Column("period_type", sa.String(length=16), nullable=False),
        sa.Column("custom_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("custom_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("warning_threshold_pct", sa.Integer(), nullable=False),
        sa.Column("enforce", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("include_member_usage", sa.Boolean(), nullable=False),
        sa.Column("hold_until_released", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(length=1024), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "credit_limit >= 0", name=op.f("ck_credit_limit_credit_limit_non_negative")
        ),
        sa.CheckConstraint(
            "warning_threshold_pct >= 1 AND warning_threshold_pct <= 100",
            name=op.f("ck_credit_limit_warning_threshold_range"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["utility_user.id"],
            name=op.f("fk_credit_limit_created_by_id_utility_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_limit")),
        sa.UniqueConstraint("entity_type", "entity_id", name="entity"),
    )
    with op.batch_alter_table("credit_limit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_credit_limit_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_credit_limit_entity_type"), ["entity_type"], unique=False
        )

    op.create_table(
        "cx_application_project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["cx_application.id"],
            name=op.f("fk_cx_application_project_application_id_cx_application"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cx_application_project")),
        sa.UniqueConstraint("application_id", "project_id", name="application_project"),
    )
    with op.batch_alter_table("cx_application_project", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cx_application_project_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cx_application_project_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "cx_group_membership",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("inherited", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["cx_group.id"],
            name=op.f("fk_cx_group_membership_group_id_cx_group"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["cx_user.id"],
            name=op.f("fk_cx_group_membership_user_id_cx_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cx_group_membership")),
        sa.UniqueConstraint("group_id", "user_id", name="group_user"),
    )
    with op.batch_alter_table("cx_group_membership", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cx_group_membership_group_id"), ["group_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cx_group_membership_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "cx_project_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("group_id", sa.String(length=64), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["cx_project.id"],
            name=op.f("fk_cx_project_group_project_id_cx_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cx_project_group")),
        sa.UniqueConstraint("project_id", "group_id", name="project_group"),
    )
    with op.batch_alter_table("cx_project_group", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cx_project_group_group_id"), ["group_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cx_project_group_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "exemption",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("entity_label", sa.String(length=512), nullable=True),
        sa.Column("reason", sa.String(length=512), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["utility_user.id"],
            name=op.f("fk_exemption_created_by_id_utility_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exemption")),
        sa.UniqueConstraint("entity_type", "entity_id", name="entity"),
    )
    with op.batch_alter_table("exemption", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exemption_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_exemption_entity_type"), ["entity_type"], unique=False)

    op.create_table(
        "usage_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("view_by", sa.String(length=16), nullable=False),
        sa.Column("subject_key", sa.String(length=320), nullable=False),
        sa.Column("subject_name", sa.String(length=320), nullable=True),
        sa.Column("subject_email", sa.String(length=320), nullable=True),
        sa.Column("entity_type", sa.String(length=16), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("credits_used", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("percent_of_total", sa.Float(), nullable=True),
        sa.Column("transactions", sa.Integer(), nullable=True),
        sa.Column("actions", sa.JSON(), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["usage_snapshot.id"],
            name=op.f("fk_usage_record_snapshot_id_usage_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_record")),
        sa.UniqueConstraint("snapshot_id", "view_by", "subject_key", name="snapshot_subject"),
    )
    with op.batch_alter_table("usage_record", schema=None) as batch_op:
        batch_op.create_index("ix_usage_record_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_record_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_usage_record_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_usage_record_snapshot_id"), ["snapshot_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_usage_record_subject_key"), ["subject_key"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_usage_record_view_by"), ["view_by"], unique=False)

    op.create_table(
        "utility_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["utility_user.id"],
            name=op.f("fk_utility_session_user_id_utility_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_utility_session")),
    )
    with op.batch_alter_table("utility_session", schema=None) as batch_op:
        batch_op.create_index(
            "ix_utility_session_expiry", ["idle_expires_at", "absolute_expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_utility_session_session_token_hash"), ["session_token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_utility_session_user_id"), ["user_id"], unique=False)

    op.create_table(
        "enforcement_action",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("entity_label", sa.String(length=512), nullable=True),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("target_label", sa.String(length=512), nullable=True),
        sa.Column("limit_id", sa.Integer(), nullable=True),
        sa.Column("period_key", sa.String(length=64), nullable=True),
        sa.Column("undo_snapshot", sa.JSON(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_by_id", sa.Integer(), nullable=True),
        sa.Column("reversal_reason", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["limit_id"],
            ["credit_limit.id"],
            name=op.f("fk_enforcement_action_limit_id_credit_limit"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_id"],
            ["utility_user.id"],
            name=op.f("fk_enforcement_action_reversed_by_id_utility_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enforcement_action")),
    )
    with op.batch_alter_table("enforcement_action", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_enforcement_action_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_enforcement_action_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_enforcement_action_idempotency_key"), ["idempotency_key"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_enforcement_action_limit_id"), ["limit_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_enforcement_action_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_enforcement_action_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            "ix_enforcement_action_target_status",
            ["target_type", "target_id", "status"],
            unique=False,
        )

    op.create_table(
        "limit_period_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("limit_id", sa.Integer(), nullable=False),
        sa.Column("period_key", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("credits_used", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("baseline_credits", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reported_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("usage_available", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("warned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("breached_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("restricted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("restored_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["limit_id"],
            ["credit_limit.id"],
            name=op.f("fk_limit_period_state_limit_id_credit_limit"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_limit_period_state")),
        sa.UniqueConstraint("limit_id", "period_key", name="limit_period"),
    )
    with op.batch_alter_table("limit_period_state", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_limit_period_state_limit_id"), ["limit_id"], unique=False
        )

    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("entity_label", sa.String(length=512), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=160), nullable=True),
        sa.Column("enforcement_action_id", sa.Integer(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["enforcement_action_id"],
            ["enforcement_action.id"],
            name=op.f("fk_notification_enforcement_action_id_enforcement_action"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_notification_dedupe_key")),
    )
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notification_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notification_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_enforcement_action_id"),
            ["enforcement_action_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_notification_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notification_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notification_severity"), ["severity"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_severity"))
        batch_op.drop_index(batch_op.f("ix_notification_entity_type"))
        batch_op.drop_index(batch_op.f("ix_notification_entity_id"))
        batch_op.drop_index(batch_op.f("ix_notification_enforcement_action_id"))
        batch_op.drop_index(batch_op.f("ix_notification_created_at"))
        batch_op.drop_index(batch_op.f("ix_notification_category"))

    op.drop_table("notification")
    with op.batch_alter_table("limit_period_state", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_limit_period_state_limit_id"))

    op.drop_table("limit_period_state")
    with op.batch_alter_table("enforcement_action", schema=None) as batch_op:
        batch_op.drop_index("ix_enforcement_action_target_status")
        batch_op.drop_index(batch_op.f("ix_enforcement_action_target_id"))
        batch_op.drop_index(batch_op.f("ix_enforcement_action_status"))
        batch_op.drop_index(batch_op.f("ix_enforcement_action_limit_id"))
        batch_op.drop_index(batch_op.f("ix_enforcement_action_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_enforcement_action_entity_type"))
        batch_op.drop_index(batch_op.f("ix_enforcement_action_entity_id"))

    op.drop_table("enforcement_action")
    with op.batch_alter_table("utility_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_utility_session_user_id"))
        batch_op.drop_index(batch_op.f("ix_utility_session_session_token_hash"))
        batch_op.drop_index("ix_utility_session_expiry")

    op.drop_table("utility_session")
    with op.batch_alter_table("usage_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_record_view_by"))
        batch_op.drop_index(batch_op.f("ix_usage_record_subject_key"))
        batch_op.drop_index(batch_op.f("ix_usage_record_snapshot_id"))
        batch_op.drop_index(batch_op.f("ix_usage_record_entity_type"))
        batch_op.drop_index(batch_op.f("ix_usage_record_entity_id"))
        batch_op.drop_index("ix_usage_record_entity")

    op.drop_table("usage_record")
    with op.batch_alter_table("exemption", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exemption_entity_type"))
        batch_op.drop_index(batch_op.f("ix_exemption_entity_id"))

    op.drop_table("exemption")
    with op.batch_alter_table("cx_project_group", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cx_project_group_project_id"))
        batch_op.drop_index(batch_op.f("ix_cx_project_group_group_id"))

    op.drop_table("cx_project_group")
    with op.batch_alter_table("cx_group_membership", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cx_group_membership_user_id"))
        batch_op.drop_index(batch_op.f("ix_cx_group_membership_group_id"))

    op.drop_table("cx_group_membership")
    with op.batch_alter_table("cx_application_project", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cx_application_project_project_id"))
        batch_op.drop_index(batch_op.f("ix_cx_application_project_application_id"))

    op.drop_table("cx_application_project")
    with op.batch_alter_table("credit_limit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credit_limit_entity_type"))
        batch_op.drop_index(batch_op.f("ix_credit_limit_entity_id"))

    op.drop_table("credit_limit")
    with op.batch_alter_table("utility_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_utility_user_username"))

    op.drop_table("utility_user")
    with op.batch_alter_table("usage_snapshot", schema=None) as batch_op:
        batch_op.drop_index("ix_usage_snapshot_view_time")
        batch_op.drop_index(batch_op.f("ix_usage_snapshot_view_by"))
        batch_op.drop_index(batch_op.f("ix_usage_snapshot_collected_at"))

    op.drop_table("usage_snapshot")
    op.drop_table("unresolved_subject")
    with op.batch_alter_table("scheduler_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduler_run_started_at"))

    op.drop_table("scheduler_run")
    op.drop_table("scheduler_lock")
    op.drop_table("login_attempt")
    op.drop_table("dimension_state")
    with op.batch_alter_table("cx_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cx_user_username"))
        batch_op.drop_index(batch_op.f("ix_cx_user_email"))

    op.drop_table("cx_user")
    with op.batch_alter_table("cx_project", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cx_project_name"))

    op.drop_table("cx_project")
    with op.batch_alter_table("cx_group", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cx_group_parent_id"))
        batch_op.drop_index(batch_op.f("ix_cx_group_name"))

    op.drop_table("cx_group")
    op.drop_table("cx_connection")
    with op.batch_alter_table("cx_application", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cx_application_name"))

    op.drop_table("cx_application")
    with op.batch_alter_table("audit_log_entry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_entry_target_type"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entry_target_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entry_occurred_at"))
        batch_op.drop_index("ix_audit_log_entry_action_time")
        batch_op.drop_index(batch_op.f("ix_audit_log_entry_action"))

    op.drop_table("audit_log_entry")
    op.drop_table("app_setting")
    # ### end Alembic commands ###
